### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by talimarcus**
Updated demo page to new format.

@Menkhaus-ge I noticed that the coloring of the code sections doesn't show up in shadow dom (on any of our demo pages)

### CODE REVIEW

**Comment by katemenkhaus** [comment]
- Starter kit should be a devDependency. Under Install the module change to --save-dev. 
- Under Use it in your project: remove typography import
- Under Dependencies: remove typography
- There shouldn't be a mention of typography anywhere. Double check the readme.md doesn't mention it.  

- Did you look to see if we could replace inuit-clearfix with px-clearfix-design?

**Comment by talimarcus** [comment]
@Menkhaus-ge removed typography and push the sass-doc change to change to --save-dev.

We decided to deal with clearfix tomorrow.

**Comment by katemenkhaus** [comment]
The `Import it in your Sass` section of the demo doesn't apply to starter kit. The purpose of starter kit is to have it bring in all the base dependencies through bower and give you a starting point for creating your own scss file. 
Otherwise looks good.

**Comment by talimarcus** [comment]
@Menkhaus-ge I added a property to hide the "Import it in your Sass" section, see here: https://github.com/PredixDev/px-sass-doc/pull/7

**Pull request merged**
